// Baseline IDs and categories; keep synchronized with source inventories.
export const facilityRegistry: Record<string, Record<string, string>> = {
  'toa-baja': {
    'shelter-1': 'shelter',
    'shelter-2': 'shelter',
    'shelter-3': 'shelter',
    'shelter-4': 'shelter',
    'shelter-5': 'shelter',
    'shelter-6': 'shelter',
    'shelter-7': 'shelter',
    'shelter-8': 'shelter',
    'shelter-9': 'shelter',
    'shelter-10': 'shelter',
    'shelter-11': 'shelter',
    'shelter-12': 'shelter',
    'siren-1': 'siren',
    'siren-2': 'siren',
    'siren-3': 'siren',
    'siren-4': 'siren',
    'siren-5': 'siren',
    'siren-6': 'siren',
    'siren-7': 'siren',
    'siren-8': 'siren',
    'siren-9': 'siren',
    'siren-10': 'siren',
    'siren-11': 'siren',
    'siren-12': 'siren',
    'siren-13': 'siren',
    'siren-14': 'siren',
    'police-levittown': 'police',
    'police-pueblo': 'police',
    'police-municipal': 'police',
    'fire-toa-baja': 'fire',
    'health-toa-baja': 'health',
  },
  catano: {
    'catano-shelter-1': 'shelter',
    'catano-shelter-2': 'shelter',
    'catano-health-5150833707': 'health',
    'catano-police-533099600': 'police',
    'catano-fire-535083126': 'fire',
    'catano-health-952097685': 'health',
  },
};
